# Generated by Django 3.1.6 on 2021-02-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210207_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='starter',
            new_name='Author',
        ),
    ]
