# Generated by Django 3.1.6 on 2021-02-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_board_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['last_updated']},
        ),
    ]
