# Generated by Django 3.1.6 on 2021-02-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210208_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-pk']},
        ),
    ]
